### ISSUE TITLE
As a User I want to Dynamically change Twitch Stream Subjects

### ISSUE THREAD

**Issue by AnnaSasDev** [code-of-chaos/novalab-cs#2]
## General Info
As A user I want to have the ability to change my Twitch Stream subject through the NovaLab Website.
I want to store a list of "frequently used" stream subject names so I can quickly reuse them when needed.
I also want to tie a special component to the tracked twitch stream subject so this can be displayed in the stream overlay on OBS.

---
### Functional Requirements
- [x] User is able to insert new Stream Subject
- [ ] User is able to update / delete stream subjects
- [x] User is able to push selected Stream Subject to Twitch 
- [ ] User is able to connect a Stream Subject to an OBS Component
- [ ] User is able to retrieve a stream subjecs's OBS component through a static https address (no headers, aka no auth)

### Technical Requirements
- [x] Table for Tracked Stream Subjects
- [x] CRUD API endpoint for Tracked Stream Subjects

---
## Tasks
- [ ] see requirements
